"""initial schema

Revision ID: 18bc0ebb5d75
Revises:
Create Date: 2026-07-22 22:07:46.648175
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '18bc0ebb5d75'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gmail_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('target_industries', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'ACTIVE', 'PAUSED', 'COMPLETED', name='campaignstatus', native_enum=False, length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('target_industries', sa.JSON(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=True)
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_recruiter_user_email')
    )
    op.create_index(op.f('ix_recruiters_email'), 'recruiters', ['email'], unique=False)
    op.create_index(op.f('ix_recruiters_user_id'), 'recruiters', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'OUTREACH_SENT', 'FOLLOW_UP', 'REPLIED', 'INTERESTED', 'SCHEDULING', 'INTERVIEW_SCHEDULED', 'NOT_INTERESTED', 'NO_RESPONSE', 'UNSUBSCRIBED', 'CLOSED', name='applicationstatus', native_enum=False, length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'recruiter_id', name='uq_application_campaign_recruiter')
    )
    op.create_index(op.f('ix_applications_campaign_id'), 'applications', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_applications_recruiter_id'), 'applications', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('email_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threads_application_id'), 'email_threads', ['application_id'], unique=False)
    op.create_index(op.f('ix_email_threads_gmail_thread_id'), 'email_threads', ['gmail_thread_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('SENT', 'RECEIVED', name='emaildirection', native_enum=False, length=12), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'QUEUED', 'SENT', 'FAILED', 'RECEIVED', name='emailstatus', native_enum=False, length=12), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=True),
    sa.Column('to_address', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('intent', sa.Enum('INTERESTED', 'NOT_INTERESTED', 'SCHEDULING', 'QUESTION', 'OUT_OF_OFFICE', 'UNSUBSCRIBE', 'OTHER', name='replyintent', native_enum=False, length=16), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_gmail_message_id'), 'emails', ['gmail_message_id'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_message_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index(op.f('ix_email_threads_gmail_thread_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_application_id'), table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_recruiter_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_campaign_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_recruiters_user_id'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_email'), table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
