"""Render the checked-in API reference from the running application.

Four artifacts, all under ``docs/api/``, all generated and none hand-edited:

``openapi.json``
    The published schema, byte-identical to what ``/openapi.json`` serves. In
    the repository so that a client generator, a diff on a pull request, or a
    reviewer without the app running can all read it.
``API-REFERENCE.md``
    The same thing for a human: every operation grouped by resource, with its
    authentication requirement, its budget and the codes it can answer.
``ERRORS.md``
    The failures, indexed by status code rather than by route — the direction
    somebody actually arrives from, holding a 409 and wanting to know why.
``ENVIRONMENT.md``
    Every setting ``Settings`` accepts, from :mod:`app.core.settings_docs`.

Kept honest by regeneration, not by review: :mod:`tests.test_api_catalog`
rebuilds all four in memory and fails if the files on disk differ, so a new
route or a new setting cannot land with the documents describing the old shape.
"""
from __future__ import annotations

import json
import pathlib
from collections import defaultdict

from fastapi import FastAPI

from app.core.apidocs import (
    STATUS_GUIDE,
    TAG_DESCRIPTIONS,
    RouteDoc,
    enrich,
    route_docs,
)
from app.core.settings_docs import SettingDoc, catalog

_GENERATED = (
    "<!-- Generated by `python -m app.core.docgen` (backend/). Do not edit by "
    "hand: tests/test_api_catalog.py regenerates this file and fails on a "
    "difference. -->"
)


def docs_dir() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parents[3] / "docs" / "api"


def _anchor(text: str) -> str:
    """A GitHub-flavoured heading anchor.

    Punctuation is dropped rather than replaced — "AI (OpenRouter)" anchors as
    ``#ai-openrouter``, and a link built by substituting hyphens for the
    brackets points at nothing.
    """
    slug = "".join(c if c.isalnum() or c in " -" else "" for c in text.lower())
    return slug.replace(" ", "-")


def _one_line(text: str, limit: int = 160) -> str:
    """First sentence-ish of a description, flattened for a table cell."""
    flat = " ".join(text.split())
    if len(flat) <= limit:
        return flat
    return flat[: limit - 1].rsplit(" ", 1)[0] + "…"


# ---------------------------------------------------------------------------
# openapi.json
# ---------------------------------------------------------------------------


def render_openapi(app: FastAPI) -> str:
    # sort_keys so a regenerated file diffs on content rather than on dict
    # ordering, and a trailing newline so the file ends the way every other
    # text file in the repository does.
    return json.dumps(enrich(app), indent=2, sort_keys=True) + "\n"


# ---------------------------------------------------------------------------
# API-REFERENCE.md
# ---------------------------------------------------------------------------


def _auth_cell(route: RouteDoc) -> str:
    if route.admin_only:
        return "admin"
    if route.authenticated:
        return "bearer"
    return "public"


def _limit_cell(route: RouteDoc) -> str:
    if not route.rate_limit:
        return "—"
    limit = route.rate_limit
    return (
        f"{limit['max_requests']}/{limit['window_seconds']}s "
        f"per {limit['keyed_by']} (`{limit['scope']}`)"
    )


def render_reference(app: FastAPI) -> str:
    routes = route_docs(app)
    by_tag: dict[str, list[RouteDoc]] = defaultdict(list)
    for route in routes:
        by_tag[route.tag].append(route)

    order = [tag for tag, _ in TAG_DESCRIPTIONS if tag in by_tag]
    order += sorted(tag for tag in by_tag if tag not in dict(TAG_DESCRIPTIONS))
    descriptions = dict(TAG_DESCRIPTIONS)

    out: list[str] = [
        "# API reference",
        "",
        _GENERATED,
        "",
        f"{len(routes)} operations across {len(by_tag)} resource groups. The "
        "machine-readable form is [`openapi.json`](openapi.json); the failure "
        "codes are indexed by code in [`ERRORS.md`](ERRORS.md); the settings "
        "that change any of this behaviour are in "
        "[`ENVIRONMENT.md`](ENVIRONMENT.md).",
        "",
        "## Authentication",
        "",
        "Every route marked `bearer` or `admin` expects "
        "`Authorization: Bearer <token>`.",
        "",
        "1. `POST /api/v1/auth/register` creates the account and returns a "
        "token; `POST /api/v1/auth/login` takes "
        "`application/x-www-form-urlencoded` with `username` (the email "
        "address) and `password` and returns the same shape. Both are limited "
        "by client address, not by user — they are the two endpoints with no "
        "authenticated caller to key on.",
        "2. The token is a JWT signed with `JWT_SECRET`, valid for "
        "`ACCESS_TOKEN_EXPIRE_MINUTES` (a day by default).",
        "3. **There is no refresh endpoint.** A token is used until it expires "
        "and then replaced by logging in again. Adding one would mean issuing "
        "a longer-lived credential, and the revocation model below is built "
        "around short ones.",
        "4. Tokens carry a `token_version` claim checked against the account on "
        "every request. Changing a password increments it, which revokes every "
        "outstanding token for that account at once — including the one making "
        "the change. Those requests answer `401` with "
        "`Session has been revoked; sign in again`, which a client must treat "
        "as a logout rather than as a retryable failure.",
        "5. `admin` routes additionally require `is_admin`. The role is granted "
        "at login to addresses listed in `ADMIN_EMAILS`, so a newly listed "
        "address becomes an administrator on its next sign-in, not on restart.",
        "",
        "### Gmail OAuth",
        "",
        "Separate from the above, and per user rather than per deployment. "
        "`GET /api/v1/gmail/authorize` returns Google's consent URL carrying a "
        "signed `state`; the user consents; Google redirects to "
        "`GET /api/v1/gmail/callback`, which verifies `state`, exchanges the "
        "code and stores the refresh token encrypted with "
        "`TOKEN_ENCRYPTION_KEY`. The callback is the one authenticated-feeling "
        "route reached without a bearer token — the `state` parameter is what "
        "identifies the user. A revoked or expired grant is recorded on the "
        "account rather than raised, so subsequent polls report "
        "`gmail_unconfigured` instead of failing.",
        "",
        "### Public routes",
        "",
        "The `tracking` group is reached by a recipient's mail client or "
        "browser and cannot carry a token. Those routes are identified by an "
        "opaque per-message token in the path or query, never by user id.",
        "",
        "## Rate limits",
        "",
        "Two limiters. Per-user limits key on the authenticated account and "
        "guard work that costs money or holds a worker; per-address limits key "
        "on the client address and guard the credential surface. Scopes are "
        "separate budgets — spending one never refuses another.",
        "",
        "A refusal is `429` with `Retry-After` in whole seconds, plus "
        "`RateLimit-Limit`, `RateLimit-Remaining` and `RateLimit-Reset`. "
        "Successful responses on a limited route carry `RateLimit-Limit` too.",
        "",
        "> Behind a reverse proxy, per-address limits are only as correct as "
        "`TRUSTED_PROXY_HOPS`. Left at 0 with a proxy in front, every caller "
        "shares one bucket and ten failed logins refuse the login route for "
        "the whole deployment.",
        "",
    ]

    metered = sorted(
        (r for r in routes if r.rate_limit),
        key=lambda r: (r.rate_limit["scope"], r.path),  # type: ignore[index]
    )
    out += ["| Scope | Budget | Keyed by | Endpoints |", "| --- | --- | --- | --- |"]
    by_scope: dict[str, list[RouteDoc]] = defaultdict(list)
    for route in metered:
        by_scope[route.rate_limit["scope"]].append(route)  # type: ignore[index]
    for scope in sorted(by_scope):
        group = by_scope[scope]
        limit = group[0].rate_limit
        endpoints = "<br>".join(f"`{r.method} {r.path}`" for r in group)
        out.append(
            f"| `{scope}` | {limit['max_requests']} per "  # type: ignore[index]
            f"{limit['window_seconds']}s | {limit['keyed_by']} | "  # type: ignore[index]
            f"{endpoints} |"
        )
    out += ["", "## Webhooks and callbacks", "", WEBHOOKS_PROSE, ""]
    public = [r for r in routes if not r.authenticated]
    out += [
        "| Method | Path | Called by | How the caller is identified |",
        "| --- | --- | --- | --- |",
    ]
    for route in public:
        caller, identity = _caller_of(route)
        out.append(f"| `{route.method}` | `{route.path}` | {caller} | {identity} |")
    out += ["", "## Errors", "", ERRORS_SUMMARY, ""]

    out += ["## Resources", ""]
    for tag in order:
        out.append(f"- [{tag}](#{_anchor(tag)}) — {len(by_tag[tag])} operations")
    out.append("")

    for tag in order:
        out += [f"## {tag}", ""]
        if tag in descriptions:
            out += [descriptions[tag], ""]
        out += [
            "| Method | Path | Auth | Rate limit | Responses | Summary |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for route in by_tag[tag]:
            codes = " ".join(str(c) for c in route.status_codes)
            out.append(
                f"| `{route.method}` | `{route.path}` | {_auth_cell(route)} | "
                f"{_limit_cell(route)} | {codes} | {_one_line(route.summary, 90)} |"
            )
        out.append("")

    return "\n".join(out).rstrip() + "\n"


WEBHOOKS_PROSE = (
    "Everything the API answers without a bearer token, and why. None of these "
    "are reachable by a client of the product — they exist because something "
    "outside it calls in.\n\n"
    "**`POST /api/v1/gmail/webhook`** is the Cloud Pub/Sub push subscription "
    "for Gmail mailbox changes. Its only gate is the `?token=` query "
    "parameter, matched against `GMAIL_PUBSUB_TOKEN`, so that value is a "
    "credential and belongs in the URL registered with Pub/Sub and nowhere "
    "else. It answers `204` to everything — a valid notification, a bad token, "
    "an unparseable body — because Pub/Sub retries with backoff on any "
    "non-2xx, and retrying a message that will never parse is a loop rather "
    "than a recovery. Failures are logged, not returned.\n\n"
    "**`GET /api/v1/gmail/callback`** is the OAuth redirect target. Google "
    "sends the user here with `code` and `state`; `state` is signed and is "
    "what identifies the user, since the browser arriving is not carrying a "
    "bearer token. It must match the URI registered on the OAuth client "
    "exactly (`GOOGLE_OAUTH_REDIRECT_URI`), or Google refuses before any code "
    "is issued.\n\n"
    "**The tracking routes** are hit by a recipient's mail client or browser. "
    "`GET /api/v1/t/o/{token}.gif` returns the pixel; "
    "`GET /api/v1/t/c/{token}` records the click and answers `302` to the "
    "decoded target. Both are identified by an opaque per-message token, never "
    "by user id, and both answer normally when the token is unknown — a "
    "tracking endpoint that errored would show a broken image in somebody's "
    "inbox. Set `EMAIL_TRACKING_ENABLED=false` to stop stamping them into "
    "outbound mail.\n\n"
    "**The unsubscribe routes** back the `List-Unsubscribe` header. The `GET` "
    "is the human-facing link; the `POST` is RFC 8058 one-click, which mail "
    "providers call themselves with no user involved — which is why it cannot "
    "require a confirmation step. `/api/v1/unsubscribe` opts a recruiter out "
    "of outreach; `/api/v1/digest/unsubscribe` opts a user out of the weekly "
    "digest. They are different lists.\n"
)


def _caller_of(route: RouteDoc) -> tuple[str, str]:
    """Who reaches a public route, and what stands in for authentication.

    Keyed on the path rather than inferred, and driven off the generated list
    of unauthenticated routes — so a new public route appears in the table
    immediately, with an explicit "not described yet" rather than by being
    silently absent.
    """
    table = {
        "/api/v1/gmail/webhook": ("Google Cloud Pub/Sub", "`?token=` query parameter"),
        "/api/v1/gmail/callback": ("Google, redirecting the user", "signed `state`"),
        "/api/v1/t/o/{token}.gif": ("recipient's mail client", "opaque path token"),
        "/api/v1/t/c/{token}": ("recipient's browser", "opaque path token"),
        "/api/v1/unsubscribe": (
            "recipient, or their mail provider",
            "opaque token",
        ),
        "/api/v1/digest/unsubscribe": (
            "user, or their mail provider",
            "opaque token",
        ),
        "/api/v1/auth/login": ("any client", "credentials in the body"),
        "/api/v1/auth/register": ("any client", "n/a — this creates the account"),
        "/api/v1/health": ("monitoring", "n/a"),
        "/": ("anyone", "n/a"),
        # Not a callback, and the only unauthenticated route in an otherwise
        # fully-authenticated router. It is read by the SPA to tell "no jobs
        # found" from "this deployment cannot reach Google Jobs", and it
        # discloses which discovery sources are configured — booleans and a
        # fixed list of public board names, no keys — to anyone who asks.
        # Listed here because a public route that nobody meant to be public is
        # exactly what this table exists to surface.
        "/api/v1/jobs/providers/status": (
            "the SPA",
            "**nothing** — public, discloses which providers are configured",
        ),
    }
    return table.get(route.path, ("—", "**not described** — add it to `_caller_of`"))


ERRORS_SUMMARY = (
    "Every failure, including an unhandled one, answers with "
    "`{\"detail\": \"...\"}`; a 500 adds `\"request_id\"`, which is also the "
    "`X-Request-ID` response header. A client's error handler therefore reads "
    "one shape for every code. Full catalogue in [`ERRORS.md`](ERRORS.md)."
)


# ---------------------------------------------------------------------------
# ERRORS.md
# ---------------------------------------------------------------------------

# What to do about each code, written for whoever is holding the response.
RESOLUTION: dict[int, str] = {
    400: (
        "Read `detail`: it names the value that cannot be acted on. Fix the "
        "request. Retrying it unchanged always fails."
    ),
    401: (
        "If `detail` is `Could not validate credentials`, the token is "
        "missing, malformed or expired — log in again. If it is "
        "`Session has been revoked; sign in again`, the account's password "
        "changed since this token was issued and every token for it is dead; "
        "the client must clear its stored token and show the login screen "
        "rather than retry."
    ),
    403: (
        "`Inactive user` means the account is disabled — nothing the client "
        "can do. `Administrator access is required` means the route is "
        "admin-only; grant the role by adding the address to `ADMIN_EMAILS` "
        "and signing in again, or through the admin API."
    ),
    404: (
        "The id does not exist, or it belongs to another account. Those are "
        "deliberately the same answer, so do not read a 404 as proof the "
        "resource is absent. Re-list the collection rather than retrying the "
        "id."
    ),
    409: (
        "The resource is in a state that refuses this call — an illegal "
        "transition, a duplicate, or a writer that got there first. Re-read "
        "the resource and decide from its current state; a blind retry either "
        "fails identically or acts on a stale assumption."
    ),
    410: (
        "The artifact was deleted by its retention sweep "
        "(`FORM_APPLY_ARTIFACT_RETENTION_DAYS`). It is not coming back. Stop "
        "offering the link."
    ),
    413: (
        "The upload is over `MAX_UPLOAD_MB`. `detail` names the file and the "
        "ceiling."
    ),
    415: (
        "The file's content type is not one the parser handles. `detail` "
        "lists what is accepted."
    ),
    422: (
        "Request validation. The body's `detail` is a list of "
        "`{loc, msg, type}` naming each offending field. Where a handler "
        "raises 422 by hand, `detail` is a sentence instead — the value "
        "parsed but cannot mean anything."
    ),
    429: (
        "Wait `Retry-After` seconds, then retry once. Do not retry "
        "immediately: the limit is a sliding window and an early retry is "
        "refused again, which is how a rate limit becomes a retry storm. On a "
        "per-address scope behind a proxy, check `TRUSTED_PROXY_HOPS` before "
        "concluding the caller was actually over budget."
    ),
    500: (
        "Nothing the client can fix. Capture `request_id` from the body — the "
        "same value is on the server's log record — and report it. The detail "
        "is always the constant string; the traceback is deliberately not sent."
    ),
    502: (
        "An upstream failed. `detail` carries the upstream's message. "
        "Retryable, with backoff."
    ),
    503: (
        "A dependency this route needs is not configured or not reachable — "
        "no model provider in the chain, no connected mailbox, "
        "`TOKEN_ENCRYPTION_KEY` unset, or workers disabled. `detail` names "
        "which. Operator action, not client action; check `/api/v1/health`."
    ),
}


def render_errors(app: FastAPI) -> str:
    routes = route_docs(app)

    # code -> detail string -> the operations that can answer with it.
    #
    # Seeded from the published document rather than from the raise sites, so
    # the catalogue covers exactly what the schema promises. The two are not
    # the same set: FastAPI generates the validation `422` on every operation
    # that takes a body or a typed parameter, and nothing in this codebase
    # raises it there — indexing only what routers raise left the single most
    # common failure in the API absent from the catalogue of failures.
    published = enrich(app)["paths"]
    index: dict[int, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    for route in routes:
        where = f"`{route.method} {route.path}`"
        operation = published.get(route.path, {}).get(route.method.lower(), {})
        for code in operation.get("responses", {}):
            if code.isdigit() and int(code) >= 400:
                index[int(code)].setdefault("", []).append(where)
        for err in route.errors:
            if err.status_code < 400:
                continue
            index[err.status_code][err.detail or "(no detail)"].append(where)

    out: list[str] = [
        "# Error catalogue",
        "",
        _GENERATED,
        "",
        "## The body",
        "",
        "```json",
        '{ "detail": "Campaign is already running", "request_id": "…" }',
        "```",
        "",
        "`detail` is present on every error. `request_id` is present on `500` "
        "and mirrors the `X-Request-ID` response header; on other codes read "
        "the header. Validation failures (`422` raised by FastAPI rather than "
        "by a handler) put a list of `{loc, msg, type}` objects in `detail` "
        "instead of a string — that is the one shape variation, and it is "
        "FastAPI's.",
        "",
        "## Codes",
        "",
        "| Code | Meaning | Operations that can return it |",
        "| --- | --- | --- |",
    ]
    for code in sorted(index):
        title, guide = STATUS_GUIDE.get(code, ("Error", ""))
        count = len({op for ops in index[code].values() for op in ops})
        out.append(f"| [{code}](#{code}-{_anchor(title)}) | {title} | {count} |")
    out.append("")

    for code in sorted(index):
        title, guide = STATUS_GUIDE.get(code, ("Error", ""))
        out += [f"## {code} {title}", "", guide, ""]
        out += ["**Resolution.** " + RESOLUTION.get(code, "—"), ""]

        details = {d: ops for d, ops in index[code].items() if d}
        if details:

            out += ["| `detail` | Raised by |", "| --- | --- |"]
            for detail in sorted(details):
                ops = sorted(set(details[detail]))
                shown = ", ".join(ops[:6])
                if len(ops) > 6:
                    shown += f", and {len(ops) - 6} more"
                out.append(f"| `{detail}` | {shown} |")
            out.append("")
        else:
            implied = sorted({op for ops in index[code].values() for op in ops})
            out += [
                f"Not raised with a fixed message; it follows from how a route "
                f"is mounted. {len(implied)} operations can return it.",
                "",
            ]

    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------------------
# ENVIRONMENT.md
# ---------------------------------------------------------------------------


def _default_cell(setting: SettingDoc) -> str:
    if setting.secret and setting.default == "(secret)":
        return "_(set)_"
    if setting.default in ("''", '""'):
        return "_(blank)_"
    return f"`{setting.default}`"


def render_environment() -> str:
    settings_list = catalog()
    sections: dict[str, list[SettingDoc]] = defaultdict(list)
    for setting in settings_list:
        sections[setting.section].append(setting)

    required = [s for s in settings_list if s.required]

    out: list[str] = [
        "# Environment variables",
        "",
        _GENERATED,
        "",
        f"{len(settings_list)} settings, read from the process environment or "
        "from `.env` (both `backend/.env` and the repository-root `.env` are "
        "searched, in that order). Names are case-insensitive; unknown "
        "variables are ignored rather than refused.",
        "",
        "**Types.** `bool` accepts `true`/`false`/`1`/`0`. A `str` that reads "
        "as a list is comma-separated — with one exception: "
        "`COMPLIANCE_PHYSICAL_ADDRESS` contains commas and is a single value, "
        "so quote it in `.env`.",
        "",
        "**Required.** Every field carries a default, so nothing is required "
        "in pydantic's sense, and asking pydantic returns 151 optional "
        "settings. The table below marks the ones whose shipped default is "
        "blank or a placeholder. For most of those, blank means the feature "
        "behind them is off until a value is supplied; for a few it means "
        "*derive it* — each entry says which, and that is why the table quotes "
        "the prose rather than a verdict.",
        "",
        "**Checked at startup.** Some settings are validated when the process "
        "boots and will refuse to start on a bad value rather than "
        "misbehaving later. Those are marked, with the guard named.",
        "",
        "**`.env.example`.** The template ships the subset an operator usually "
        "sets. A setting absent from it is still settable — this catalogue, "
        "not that file, is the complete list.",
        "",
        "## Settings that ship blank",
        "",
        "| Variable | Section | What the blank default means |",
        "| --- | --- | --- |",
    ]
    for setting in required:
        out.append(
            f"| `{setting.env_var}` | {setting.section} | "
            f"{_one_line(setting.description, 110)} |"
        )
    out += ["", "## By section", ""]
    for section in sections:
        out.append(f"- [{section}](#{_anchor(section)})")
    out.append("")

    for section, group in sections.items():
        out += [f"## {section}", ""]
        for setting in group:
            flags = []
            if setting.required:
                flags.append("ships blank")
            if setting.secret:
                flags.append("secret")
            if setting.validated_by:
                flags.append(
                    "checked at startup by "
                    + ", ".join(f"`{name}`" for name in setting.validated_by)
                )
            if not setting.in_env_example:
                flags.append("not in `.env.example`")
            out += [
                f"### `{setting.env_var}`",
                "",
                f"`{setting.type_name}` · default {_default_cell(setting)}"
                + (f" · {', '.join(flags)}" if flags else ""),
                "",
            ]
            body = setting.description
            if setting.shared_description:
                body = (
                    "_Declared alongside the settings above it; the note covers "
                    "the group._\n\n" + body
                )
            out += [body, ""]

    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------------------


def render_all(app: FastAPI) -> dict[str, str]:
    """Every generated document, keyed by filename."""
    return {
        "openapi.json": render_openapi(app),
        "API-REFERENCE.md": render_reference(app),
        "ERRORS.md": render_errors(app),
        "ENVIRONMENT.md": render_environment(),
    }


def write_all() -> list[pathlib.Path]:
    from app.main import app

    target = docs_dir()
    target.mkdir(parents=True, exist_ok=True)
    written = []
    for name, body in render_all(app).items():
        path = target / name
        path.write_text(body, encoding="utf-8")
        written.append(path)
    return written


if __name__ == "__main__":  # pragma: no cover - operator entrypoint
    for path in write_all():
        print(path)
